### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by skaan07** [kevva/screenshot-promise#1]
I am aware of the fact that the problem is because of phantomjs instead of screenshot, I am still unable to use the package in centos. Below is the error message:

`Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { [Error: Command failed: tar jxf /usr/local/node_servers/ScreenShot/versions/0.0.1/ScreenShot/node_modules/phantomjs/phantomjs/phantomjs-1.9.2-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
]
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar jxf /usr/local/node_servers/ScreenShot/versions/0.0.1/ScreenShot/node_modules/phantomjs/phantomjs/phantomjs-1.9.2-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /usr/local/node_servers/ScreenShot/versions/0.0.1/ScreenShot/node_modules/phantomjs/phantomjs/phantomjs-1.9.2-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

```
at ChildProcess.exithandler (child_process.js:202:12)
at emitTwo (events.js:100:13)
at ChildProcess.emit (events.js:185:7)
at maybeClose (internal/child_process.js:850:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:90:13)
at Socket.emit (events.js:182:7)
at Pipe._onclose (net.js:475:12)
```

ScreenShotApi@0.0.0 /usr/local/node_servers/ScreenShot/versions/0.0.1/ScreenShot
├── base64-stream@0.1.3  extraneous
├── es5-shim@4.5.7  extraneous
├── object-assign@2.1.1  extraneous
├── parse-cookie-phantomjs@1.2.0  extraneous
└── stream-to-promise@1.1.0  extraneous

npm ERR! Linux 3.10.0-229.14.1.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "screenshot-promise"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.0
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.2-6 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.2-6 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/node_servers/ScreenShot/versions/0.0.1/ScreenShot/npm-debug.log
`

**Comment by kevva** [comment]
Looks like you don't have `tar` available on the command line. It's not related to this module though but to https://github.com/medium/phantomjs.
