### ISSUE TITLE
Can I capture multiple SVG within a html selector?

### ISSUE THREAD

**Issue by imtiaz-emu** [kevva/screenshot-promise#4]
In my webpage, it contains multiple SVG under a specific `section`, like below:
```
<section id="svgs">
  <svg1> 
  <svg2>
  <svg3>
</section>
```

Is it possible to capture those 3 SVGs under the section with id `svgs`? 

Is it compatible with angular 4?

**Comment by SamVerschueren** [comment]
See https://github.com/kevva/screenshot-stream#selector. It uses `document.querySelector()` under the hood, so if you can capture them with `querySelector()`, you can capture them with this library.
